homeassistant:
  packages: !include_dir_merge_named includes/packages

  # Name of the location where Home Assistant is running
  name: "ASG HA"
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  time_zone: !secret time_zone_name

## Loads default set of integrations. Do not remove.
default_config:

# Включение официального интерфейса
frontend:
  themes: !include_dir_merge_named includes/themes

# My own handmade automations
automation manual: !include_dir_merge_list automations/
# Automations I create in the UI
automation ui: !include automations.yaml

zone: !include includes/zone.yaml
counter: !include includes/counter.yaml

timer: !include_dir_merge_named includes/timers
sensor: !include_dir_merge_list includes/sensors
binary_sensor: !include_dir_merge_list includes/bin_sensors

input_boolean: !include_dir_merge_named includes/input_booleans
input_number: !include_dir_merge_named includes/input_numbers
input_select: !include_dir_merge_named includes/input_selects

switch: !include_dir_merge_list includes/switchs
template: !include_dir_merge_list includes/templates

#script: !include scripts.yaml
script: !include_dir_merge_list includes/scripts
shell_command: !include_dir_merge_list includes/shell

scene: !include scenes.yaml

mqtt: !include_dir_merge_list includes/mqtt

climate: !include_dir_merge_list includes/climates

telegram_bot: !include includes/notification/telegram_bot1.yaml
notify: !include includes/notification/notify.yaml

panel_custom: !include includes/panel_custom.yaml

# Text to speech
tts:
  - platform: google_translate

logger:
  default: warn
  logs:
    custom_components.ble_monitor: info

